### ISSUE TITLE
caller setter change causes a number of test262 failures

### ISSUE THREAD

**Issue by evilpie** [claudepache/es-legacy-function-reflection#11]
Removing the setter for `caller` makes us less strict when assigning to `.caller` for generators and other restricted functions. That causes a number of test262 failures.

I think most (probably all) of these failures for our implementation in [bug 1616378](https://bugzilla.mozilla.org/show_bug.cgi?id=1616378) are caused by this.

    test262/built-ins/Function/prototype/bind/15.3.4.5-20-3.js
    test262/built-ins/Function/prototype/bind/BoundFunction_restricted-properties.js
    test262/built-ins/GeneratorFunction/instance-restricted-properties.js
    test262/language/statements/function/13.2-22-s.js
    test262/language/statements/function/13.2-6-s.js
    test262/language/statements/function/13.2-30-s.js
    test262/language/statements/function/13.2-10-s.js
    test262/language/statements/class/restricted-properties.js
    test262/language/statements/class/definition/methods-restricted-properties.js
    test262/language/statements/generators/restricted-properties.js
    test262/language/expressions/arrow-function/ArrowFunction_restricted-properties.js
    test262/language/expressions/class/restricted-properties.js

I am not sure if becoming less strict is really desirable, most of these would probably still throw in strict-mode, which often isn't used.

**Comment by claudepache** [comment]
Those test failures are expected, yes.

The reason is that, with just a regular accessor property on `Function.prototype`, it is impossible to have the situation of the first column of the table in [analysis.md#setting-to-caller-and-arguments](https://github.com/claudepache/es-legacy-function-reflection/blob/master/analysis.md#setting-to-caller-and-arguments), and it is risky to throw unconditionally. Trade-off is needed. My priority is: I want a failed assignment to continue to throw in strict mode (which is no longer the case in SM since the day they switch to accessor). Testcase:

```js
function randomFunction() {
    "don't use strict";
}

(function () {
    "use strict";

    var randomProp = "caller";

    // should either succeed or throw
    randomFunction[randomProp] = 42;

    // should print 42 if executed
    print(randomFunction[randomProp]);
})();
```

**Comment by claudepache** [comment]
To expand my argument above: Consider that, in all the following cases, assignment fails loudly (by throwing a TypeError) in strict mode and silently in sloppy mode:

```js
var set = new Set;
set.size = 42;

var obj = Object.preventExtensions({});
obj.foo = 42;

var rx = /(?:)/;
rx.ignoreCase = true;
```

I expect that, for the following cases, the failed assignment is loud in strict mode.

```js
var unrestricted = Function("");
unrestricted.caller = 42;

var restricted = (_ => _);
restricted.caller = 42;
```

In the “restricted” case, it is a plus that the failed assignment is currently loud also in sloppy mode, but it is not that important, given that it is not the case for failed assignments in general. However, it is highly desirable that, in all cases, the failed assignment is loud in strict mode; which is what SM currently fails to do in the “unrestricted” case. 

The test262 failures mentioned by OP concern the nonessential loud failed assignment in sloppy mode for the “restricted” case. On the other hand, there don’t seem to be tests for the more important loud failed assignments in strict mode for the “unrestricted” case, because this case is currently not part of ecma262 (which this proposal aims to fix).

**Comment by evilpie** [comment]
I have thought about this a bit more and this is probably ok. Specifying our current behavior of invoking the getter first in the setter function basically just for side-effects seems silly. Losing this one restriction is a bit annoying, but really not the end of the world.
