### ISSUE TITLE
IsLeakableFunction step 5 redundant?

### ISSUE THREAD

**Issue by bathos** [claudepache/es-legacy-function-reflection#4]
5. If func.[[ECMAScriptCode]] is not an instance of FunctionBody, return false. — NOTE. This condition targets generators and async functions.
6. If func does not have a [[Construct]] internal method, return false. — NOTE. This condition targets getters, setters and methods in object literals, as well as arrow functions.

Wouldn’t the step 6 [[Construct]] test be sufficient to cover generator, async generator, and async functions? What cases of interest would exit at step 5 but not also at step 6?

**Comment by claudepache** [comment]
> Wouldn’t the step 6 [[Construct]] test be sufficient to cover generator, async generator, and async functions?

You’re right, step 5 is redundant.

(My guess is that I made the distinction between generator/async and other non-constructors, because there is such a distinction (in JSC and in proposed spec) in the set of functions that is allowed to be returned by Function#caller. But that doesn’t apply to IsLeakableFunction.)
